### ISSUE TITLE
onclick

### ISSUE THREAD

**Issue by ttojiyev** [Liverm0r/DelegateAdapters#2]
![delegate](https://user-images.githubusercontent.com/23132933/59147826-d7274000-8a19-11e9-8dbe-4911e5982c07.jpg)

How I can pass my Unit function here? If put it above Builder then I cannot catch "adapterFolders" object

**Comment by D00mch** [comment]
Hi @ttojiyev, I added an example with one possible workaround [KotlinBaseExampleActivity.kt][1]

[1]: https://github.com/Liverm0r/DelegateAdapters/blob/master/example/src/main/java/com/livermor/dumchev/delegateadapters/base/KotlinBaseExampleActivity.kt
```kotlin
    private val diffAdapter by lazy {
        DiffUtilCompositeAdapter.Builder()
                .add(GenerateItemsDelegateAdapter { generateNewData() })
                .build()
    }

    private fun generateNewData() {
        diffAdapter.swapData(MockDataFactory.prepareData())
    }
```
