### ISSUE TITLE
2.11 version not available

### ISSUE THREAD

**Issue by Sequentor** [Liverm0r/DelegateAdapters#3]
Доброго времени суток! Последняя доступная версия 2.03. На версию 2.11 ругается о недоступности! P.S. Спасибо за Адаптеры!

**Comment by D00mch** [comment]
Привет! Спасибо, была опечатка в implementation, поправил.
Если что, там ниже есть [![Build Status](https://travis-ci.org/sockeqwe/AdapterDelegates.svg?branch=master)](https://jitpack.io/#Liverm0r/delegateadapters)
В нем всегда правильная ссылка на последнюю версию.
